# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Zeke/Google Drive/dev/python/zeex/zeex/core/ui/basic/criteria.ui'
#
# Created: Mon Nov 13 22:57:17 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CriteriaDialog(object):
    def setupUi(self, CriteriaDialog):
        CriteriaDialog.setObjectName("CriteriaDialog")
        CriteriaDialog.resize(631, 376)
        self.gridLayout = QtGui.QGridLayout(CriteriaDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelFilter_2 = QtGui.QLabel(CriteriaDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilter_2.sizePolicy().hasHeightForWidth())
        self.labelFilter_2.setSizePolicy(sizePolicy)
        self.labelFilter_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFilter_2.setObjectName("labelFilter_2")
        self.gridLayout_6.addWidget(self.labelFilter_2, 0, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.btnDeleteCriteria = QtGui.QPushButton(CriteriaDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeleteCriteria.sizePolicy().hasHeightForWidth())
        self.btnDeleteCriteria.setSizePolicy(sizePolicy)
        self.btnDeleteCriteria.setObjectName("btnDeleteCriteria")
        self.gridLayout_10.addWidget(self.btnDeleteCriteria, 1, 0, 1, 1)
        self.btnPushUp = QtGui.QPushButton(CriteriaDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPushUp.sizePolicy().hasHeightForWidth())
        self.btnPushUp.setSizePolicy(sizePolicy)
        self.btnPushUp.setObjectName("btnPushUp")
        self.gridLayout_10.addWidget(self.btnPushUp, 0, 0, 1, 1)
        self.btnPushDown = QtGui.QPushButton(CriteriaDialog)
        self.btnPushDown.setObjectName("btnPushDown")
        self.gridLayout_10.addWidget(self.btnPushDown, 2, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tableViewCriteria = QtGui.QTableView(CriteriaDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewCriteria.sizePolicy().hasHeightForWidth())
        self.tableViewCriteria.setSizePolicy(sizePolicy)
        self.tableViewCriteria.setMinimumSize(QtCore.QSize(0, 50))
        self.tableViewCriteria.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tableViewCriteria.setObjectName("tableViewCriteria")
        self.gridLayout_9.addWidget(self.tableViewCriteria, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_9, 3, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEditGroup = QtGui.QLineEdit(CriteriaDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditGroup.sizePolicy().hasHeightForWidth())
        self.lineEditGroup.setSizePolicy(sizePolicy)
        self.lineEditGroup.setObjectName("lineEditGroup")
        self.gridLayout_8.addWidget(self.lineEditGroup, 1, 1, 1, 1)
        self.labelGroup = QtGui.QLabel(CriteriaDialog)
        self.labelGroup.setObjectName("labelGroup")
        self.gridLayout_8.addWidget(self.labelGroup, 0, 1, 1, 1)
        self.comboBoxCondition = QtGui.QComboBox(CriteriaDialog)
        self.comboBoxCondition.setObjectName("comboBoxCondition")
        self.comboBoxCondition.addItem("")
        self.comboBoxCondition.addItem("")
        self.comboBoxCondition.addItem("")
        self.comboBoxCondition.addItem("")
        self.comboBoxCondition.addItem("")
        self.comboBoxCondition.addItem("")
        self.comboBoxCondition.addItem("")
        self.comboBoxCondition.addItem("")
        self.comboBoxCondition.addItem("")
        self.comboBoxCondition.addItem("")
        self.gridLayout_8.addWidget(self.comboBoxCondition, 1, 3, 1, 1)
        self.labelField = QtGui.QLabel(CriteriaDialog)
        self.labelField.setObjectName("labelField")
        self.gridLayout_8.addWidget(self.labelField, 0, 2, 1, 1)
        self.comboBoxAndOr = QtGui.QComboBox(CriteriaDialog)
        self.comboBoxAndOr.setObjectName("comboBoxAndOr")
        self.comboBoxAndOr.addItem("")
        self.comboBoxAndOr.setItemText(0, "")
        self.comboBoxAndOr.addItem("")
        self.comboBoxAndOr.addItem("")
        self.gridLayout_8.addWidget(self.comboBoxAndOr, 1, 5, 1, 1)
        self.labelAndOr = QtGui.QLabel(CriteriaDialog)
        self.labelAndOr.setObjectName("labelAndOr")
        self.gridLayout_8.addWidget(self.labelAndOr, 0, 5, 1, 1)
        self.comboBoxField = QtGui.QComboBox(CriteriaDialog)
        self.comboBoxField.setObjectName("comboBoxField")
        self.gridLayout_8.addWidget(self.comboBoxField, 1, 2, 1, 1)
        self.lineEditValue = QtGui.QLineEdit(CriteriaDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditValue.sizePolicy().hasHeightForWidth())
        self.lineEditValue.setSizePolicy(sizePolicy)
        self.lineEditValue.setObjectName("lineEditValue")
        self.gridLayout_8.addWidget(self.lineEditValue, 1, 4, 1, 1)
        self.labelValue = QtGui.QLabel(CriteriaDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelValue.sizePolicy().hasHeightForWidth())
        self.labelValue.setSizePolicy(sizePolicy)
        self.labelValue.setObjectName("labelValue")
        self.gridLayout_8.addWidget(self.labelValue, 0, 4, 1, 1)
        self.labelCondition = QtGui.QLabel(CriteriaDialog)
        self.labelCondition.setObjectName("labelCondition")
        self.gridLayout_8.addWidget(self.labelCondition, 0, 3, 1, 1)
        self.btnAddCriteria = QtGui.QPushButton(CriteriaDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddCriteria.sizePolicy().hasHeightForWidth())
        self.btnAddCriteria.setSizePolicy(sizePolicy)
        self.btnAddCriteria.setObjectName("btnAddCriteria")
        self.gridLayout_8.addWidget(self.btnAddCriteria, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelGroups = QtGui.QLabel(CriteriaDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGroups.sizePolicy().hasHeightForWidth())
        self.labelGroups.setSizePolicy(sizePolicy)
        self.labelGroups.setMinimumSize(QtCore.QSize(75, 0))
        self.labelGroups.setMaximumSize(QtCore.QSize(50, 50))
        self.labelGroups.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGroups.setObjectName("labelGroups")
        self.gridLayout_2.addWidget(self.labelGroups, 0, 1, 1, 1)
        self.listViewGroups = QtGui.QListView(CriteriaDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewGroups.sizePolicy().hasHeightForWidth())
        self.listViewGroups.setSizePolicy(sizePolicy)
        self.listViewGroups.setMinimumSize(QtCore.QSize(0, 0))
        self.listViewGroups.setMaximumSize(QtCore.QSize(250, 80))
        self.listViewGroups.setObjectName("listViewGroups")
        self.gridLayout_2.addWidget(self.listViewGroups, 0, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.labelCriteria = QtGui.QLabel(CriteriaDialog)
        self.labelCriteria.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCriteria.setObjectName("labelCriteria")
        self.gridLayout_6.addWidget(self.labelCriteria, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 0, 0, 1, 1)

        self.retranslateUi(CriteriaDialog)
        QtCore.QMetaObject.connectSlotsByName(CriteriaDialog)

    def retranslateUi(self, CriteriaDialog):
        CriteriaDialog.setWindowTitle(QtGui.QApplication.translate("CriteriaDialog", "Criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFilter_2.setText(QtGui.QApplication.translate("CriteriaDialog", "FILTER", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeleteCriteria.setText(QtGui.QApplication.translate("CriteriaDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPushUp.setText(QtGui.QApplication.translate("CriteriaDialog", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPushDown.setText(QtGui.QApplication.translate("CriteriaDialog", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditGroup.setToolTip(QtGui.QApplication.translate("CriteriaDialog", "Enter name of criteria group (or leave blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGroup.setText(QtGui.QApplication.translate("CriteriaDialog", "Criteria Group", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCondition.setItemText(0, QtGui.QApplication.translate("CriteriaDialog", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCondition.setItemText(1, QtGui.QApplication.translate("CriteriaDialog", "!=", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCondition.setItemText(2, QtGui.QApplication.translate("CriteriaDialog", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCondition.setItemText(3, QtGui.QApplication.translate("CriteriaDialog", ">=", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCondition.setItemText(4, QtGui.QApplication.translate("CriteriaDialog", "<=", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCondition.setItemText(5, QtGui.QApplication.translate("CriteriaDialog", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCondition.setItemText(6, QtGui.QApplication.translate("CriteriaDialog", "LIKE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCondition.setItemText(7, QtGui.QApplication.translate("CriteriaDialog", "NOT LIKE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCondition.setItemText(8, QtGui.QApplication.translate("CriteriaDialog", "IS NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCondition.setItemText(9, QtGui.QApplication.translate("CriteriaDialog", "IS NOT NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.labelField.setText(QtGui.QApplication.translate("CriteriaDialog", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxAndOr.setItemText(1, QtGui.QApplication.translate("CriteriaDialog", "AND", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxAndOr.setItemText(2, QtGui.QApplication.translate("CriteriaDialog", "OR", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAndOr.setText(QtGui.QApplication.translate("CriteriaDialog", "And/Or", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxField.setToolTip(QtGui.QApplication.translate("CriteriaDialog", "The field to apply the criteria to", None, QtGui.QApplication.UnicodeUTF8))
        self.labelValue.setText(QtGui.QApplication.translate("CriteriaDialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCondition.setText(QtGui.QApplication.translate("CriteriaDialog", "Condition", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddCriteria.setText(QtGui.QApplication.translate("CriteriaDialog", "Add Criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGroups.setText(QtGui.QApplication.translate("CriteriaDialog", "GROUPS", None, QtGui.QApplication.UnicodeUTF8))
        self.listViewGroups.setAccessibleName(QtGui.QApplication.translate("CriteriaDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCriteria.setText(QtGui.QApplication.translate("CriteriaDialog", "CRITERIA", None, QtGui.QApplication.UnicodeUTF8))

