# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connections.ui'
#
# Created: Sun Jan 22 11:22:49 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FtpConnectionsDialog(object):
    def setupUi(self, FtpConnectionsDialog):
        FtpConnectionsDialog.setObjectName("FtpConnectionsDialog")
        FtpConnectionsDialog.resize(508, 441)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(FtpConnectionsDialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelConnections = QtGui.QLabel(FtpConnectionsDialog)
        self.labelConnections.setAlignment(QtCore.Qt.AlignCenter)
        self.labelConnections.setObjectName("labelConnections")
        self.gridLayout.addWidget(self.labelConnections, 0, 0, 1, 1)
        self.listViewConnections = QtGui.QListView(FtpConnectionsDialog)
        self.listViewConnections.setObjectName("listViewConnections")
        self.gridLayout.addWidget(self.listViewConnections, 2, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnDelete = QtGui.QPushButton(FtpConnectionsDialog)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout_2.addWidget(self.btnDelete, 0, 2, 1, 1)
        self.btnEdit = QtGui.QPushButton(FtpConnectionsDialog)
        self.btnEdit.setObjectName("btnEdit")
        self.gridLayout_2.addWidget(self.btnEdit, 0, 1, 1, 1)
        self.btnAdd = QtGui.QPushButton(FtpConnectionsDialog)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout_2.addWidget(self.btnAdd, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelHost = QtGui.QLabel(FtpConnectionsDialog)
        self.labelHost.setObjectName("labelHost")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelHost)
        self.lineEditHost = QtGui.QLineEdit(FtpConnectionsDialog)
        self.lineEditHost.setObjectName("lineEditHost")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditHost)
        self.labelUsername = QtGui.QLabel(FtpConnectionsDialog)
        self.labelUsername.setObjectName("labelUsername")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelUsername)
        self.lineEditUsername = QtGui.QLineEdit(FtpConnectionsDialog)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditUsername)
        self.labelPassword = QtGui.QLabel(FtpConnectionsDialog)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelPassword)
        self.lineEditPassword = QtGui.QLineEdit(FtpConnectionsDialog)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditPassword)
        self.labelPort = QtGui.QLabel(FtpConnectionsDialog)
        self.labelPort.setObjectName("labelPort")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelPort)
        self.lineEditPort = QtGui.QLineEdit(FtpConnectionsDialog)
        self.lineEditPort.setObjectName("lineEditPort")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditPort)
        self.gridLayout.addLayout(self.formLayout, 2, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(FtpConnectionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 1, 1, 1)
        self.label = QtGui.QLabel(FtpConnectionsDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(FtpConnectionsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), FtpConnectionsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), FtpConnectionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FtpConnectionsDialog)

    def retranslateUi(self, FtpConnectionsDialog):
        FtpConnectionsDialog.setWindowTitle(QtGui.QApplication.translate("FtpConnectionsDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.labelConnections.setText(QtGui.QApplication.translate("FtpConnectionsDialog", "Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelete.setText(QtGui.QApplication.translate("FtpConnectionsDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEdit.setText(QtGui.QApplication.translate("FtpConnectionsDialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("FtpConnectionsDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHost.setText(QtGui.QApplication.translate("FtpConnectionsDialog", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.labelUsername.setText(QtGui.QApplication.translate("FtpConnectionsDialog", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPassword.setText(QtGui.QApplication.translate("FtpConnectionsDialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPort.setText(QtGui.QApplication.translate("FtpConnectionsDialog", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FtpConnectionsDialog", "Connection Details", None, QtGui.QApplication.UnicodeUTF8))

