# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Zeke/Google Drive/dev/python/zeex/zeex/core/ui/ftp/main.ui'
#
# Created: Mon Nov 13 22:57:18 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FtpMainWindow(object):
    def setupUi(self, FtpMainWindow):
        FtpMainWindow.setObjectName("FtpMainWindow")
        FtpMainWindow.resize(1102, 847)
        self.centralwidget = QtGui.QWidget(FtpMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 2, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 12, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 11, 1, 1)
        self.btnConnect = QtGui.QPushButton(self.centralwidget)
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout_2.addWidget(self.btnConnect, 0, 8, 1, 1)
        self.lineEditHost = QtGui.QLineEdit(self.centralwidget)
        self.lineEditHost.setObjectName("lineEditHost")
        self.gridLayout_2.addWidget(self.lineEditHost, 0, 1, 1, 1)
        self.labelPort = QtGui.QLabel(self.centralwidget)
        self.labelPort.setObjectName("labelPort")
        self.gridLayout_2.addWidget(self.labelPort, 0, 6, 1, 1)
        self.labelUsername = QtGui.QLabel(self.centralwidget)
        self.labelUsername.setObjectName("labelUsername")
        self.gridLayout_2.addWidget(self.labelUsername, 0, 2, 1, 1)
        self.labelPassword = QtGui.QLabel(self.centralwidget)
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout_2.addWidget(self.labelPassword, 0, 4, 1, 1)
        self.lineEditPort = QtGui.QLineEdit(self.centralwidget)
        self.lineEditPort.setObjectName("lineEditPort")
        self.gridLayout_2.addWidget(self.lineEditPort, 0, 7, 1, 1)
        self.labelHost = QtGui.QLabel(self.centralwidget)
        self.labelHost.setObjectName("labelHost")
        self.gridLayout_2.addWidget(self.labelHost, 0, 0, 1, 1)
        self.lineEditUsername = QtGui.QLineEdit(self.centralwidget)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.gridLayout_2.addWidget(self.lineEditUsername, 0, 3, 1, 1)
        self.lineEditPassword = QtGui.QLineEdit(self.centralwidget)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout_2.addWidget(self.lineEditPassword, 0, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 10, 1, 1)
        self.comboBoxRecent = QtGui.QComboBox(self.centralwidget)
        self.comboBoxRecent.setObjectName("comboBoxRecent")
        self.gridLayout_2.addWidget(self.comboBoxRecent, 0, 9, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.treeViewRemote = QtGui.QTreeView(self.centralwidget)
        self.treeViewRemote.setObjectName("treeViewRemote")
        self.gridLayout.addWidget(self.treeViewRemote, 1, 1, 1, 1)
        self.treeViewLocal = QtGui.QTreeView(self.centralwidget)
        self.treeViewLocal.setObjectName("treeViewLocal")
        self.gridLayout.addWidget(self.treeViewLocal, 1, 0, 1, 1)
        self.lineEditLocal = QtGui.QLineEdit(self.centralwidget)
        self.lineEditLocal.setObjectName("lineEditLocal")
        self.gridLayout.addWidget(self.lineEditLocal, 0, 0, 1, 1)
        self.lineEditRemote = QtGui.QLineEdit(self.centralwidget)
        self.lineEditRemote.setObjectName("lineEditRemote")
        self.gridLayout.addWidget(self.lineEditRemote, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        FtpMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FtpMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 21))
        self.menubar.setObjectName("menubar")
        self.menuFTP = QtGui.QMenu(self.menubar)
        self.menuFTP.setObjectName("menuFTP")
        FtpMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(FtpMainWindow)
        self.statusbar.setObjectName("statusbar")
        FtpMainWindow.setStatusBar(self.statusbar)
        self.actionConnections = QtGui.QAction(FtpMainWindow)
        self.actionConnections.setObjectName("actionConnections")
        self.menuFTP.addAction(self.actionConnections)
        self.menubar.addAction(self.menuFTP.menuAction())

        self.retranslateUi(FtpMainWindow)
        QtCore.QMetaObject.connectSlotsByName(FtpMainWindow)

    def retranslateUi(self, FtpMainWindow):
        FtpMainWindow.setWindowTitle(QtGui.QApplication.translate("FtpMainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConnect.setText(QtGui.QApplication.translate("FtpMainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPort.setText(QtGui.QApplication.translate("FtpMainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelUsername.setText(QtGui.QApplication.translate("FtpMainWindow", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPassword.setText(QtGui.QApplication.translate("FtpMainWindow", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHost.setText(QtGui.QApplication.translate("FtpMainWindow", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFTP.setTitle(QtGui.QApplication.translate("FtpMainWindow", "FTP", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnections.setText(QtGui.QApplication.translate("FtpMainWindow", "Connections", None, QtGui.QApplication.UnicodeUTF8))

