# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Zeke/Google Drive/dev/python/zeex/zeex/core/ui/actions/import.ui'
#
# Created: Mon Nov 13 22:57:16 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ImportFileDialog(object):
    def setupUi(self, ImportFileDialog):
        ImportFileDialog.setObjectName("ImportFileDialog")
        ImportFileDialog.resize(624, 279)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ImportFileDialog.sizePolicy().hasHeightForWidth())
        ImportFileDialog.setSizePolicy(sizePolicy)
        self.gridLayout_7 = QtGui.QGridLayout(ImportFileDialog)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnBrowseFilePath = QtGui.QPushButton(ImportFileDialog)
        self.btnBrowseFilePath.setObjectName("btnBrowseFilePath")
        self.gridLayout_4.addWidget(self.btnBrowseFilePath, 0, 2, 1, 1)
        self.labelFilePath = QtGui.QLabel(ImportFileDialog)
        self.labelFilePath.setObjectName("labelFilePath")
        self.gridLayout_4.addWidget(self.labelFilePath, 0, 0, 1, 1)
        self.lineEditFilePath = QtGui.QLineEdit(ImportFileDialog)
        self.lineEditFilePath.setObjectName("lineEditFilePath")
        self.gridLayout_4.addWidget(self.lineEditFilePath, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditOtherSeparator = QtGui.QLineEdit(ImportFileDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOtherSeparator.sizePolicy().hasHeightForWidth())
        self.lineEditOtherSeparator.setSizePolicy(sizePolicy)
        self.lineEditOtherSeparator.setObjectName("lineEditOtherSeparator")
        self.gridLayout_3.addWidget(self.lineEditOtherSeparator, 2, 1, 1, 1)
        self.radioBtnOtherSeparator = QtGui.QRadioButton(ImportFileDialog)
        self.radioBtnOtherSeparator.setObjectName("radioBtnOtherSeparator")
        self.gridLayout_3.addWidget(self.radioBtnOtherSeparator, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.comboBoxSeparator = QtGui.QComboBox(ImportFileDialog)
        self.comboBoxSeparator.setObjectName("comboBoxSeparator")
        self.gridLayout_2.addWidget(self.comboBoxSeparator, 0, 1, 1, 1)
        self.labelSeparator = QtGui.QLabel(ImportFileDialog)
        self.labelSeparator.setObjectName("labelSeparator")
        self.gridLayout_2.addWidget(self.labelSeparator, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ImportFileDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelEncoding = QtGui.QLabel(ImportFileDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEncoding.sizePolicy().hasHeightForWidth())
        self.labelEncoding.setSizePolicy(sizePolicy)
        self.labelEncoding.setMinimumSize(QtCore.QSize(197, 0))
        self.labelEncoding.setObjectName("labelEncoding")
        self.gridLayout_6.addWidget(self.labelEncoding, 0, 0, 1, 1)
        self.comboBoxEncoding = QtGui.QComboBox(ImportFileDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxEncoding.sizePolicy().hasHeightForWidth())
        self.comboBoxEncoding.setSizePolicy(sizePolicy)
        self.comboBoxEncoding.setObjectName("comboBoxEncoding")
        self.gridLayout_6.addWidget(self.comboBoxEncoding, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBoxScrubLinebreaks = QtGui.QCheckBox(ImportFileDialog)
        self.checkBoxScrubLinebreaks.setObjectName("checkBoxScrubLinebreaks")
        self.gridLayout_5.addWidget(self.checkBoxScrubLinebreaks, 0, 2, 1, 1)
        self.checkBoxHasHeaders = QtGui.QCheckBox(ImportFileDialog)
        self.checkBoxHasHeaders.setObjectName("checkBoxHasHeaders")
        self.gridLayout_5.addWidget(self.checkBoxHasHeaders, 0, 0, 1, 1)
        self.checkBoxParseDates = QtGui.QCheckBox(ImportFileDialog)
        self.checkBoxParseDates.setObjectName("checkBoxParseDates")
        self.gridLayout_5.addWidget(self.checkBoxParseDates, 0, 1, 1, 1)
        self.checkBoxTrimSpaces = QtGui.QCheckBox(ImportFileDialog)
        self.checkBoxTrimSpaces.setObjectName("checkBoxTrimSpaces")
        self.gridLayout_5.addWidget(self.checkBoxTrimSpaces, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(ImportFileDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ImportFileDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ImportFileDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ImportFileDialog)

    def retranslateUi(self, ImportFileDialog):
        ImportFileDialog.setWindowTitle(QtGui.QApplication.translate("ImportFileDialog", "Import File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowseFilePath.setText(QtGui.QApplication.translate("ImportFileDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFilePath.setText(QtGui.QApplication.translate("ImportFileDialog", "File Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBtnOtherSeparator.setText(QtGui.QApplication.translate("ImportFileDialog", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSeparator.setText(QtGui.QApplication.translate("ImportFileDialog", "Separator:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelEncoding.setText(QtGui.QApplication.translate("ImportFileDialog", "Encoding:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxScrubLinebreaks.setText(QtGui.QApplication.translate("ImportFileDialog", "Scrub Linebreaks", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxHasHeaders.setText(QtGui.QApplication.translate("ImportFileDialog", "Has Headers", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxParseDates.setText(QtGui.QApplication.translate("ImportFileDialog", "Parse Dates", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxTrimSpaces.setText(QtGui.QApplication.translate("ImportFileDialog", "Trim Spaces", None, QtGui.QApplication.UnicodeUTF8))

