# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'merge_purge.ui'
#
# Created: Tue Dec  6 03:04:17 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MergePurgeDialog(object):
    def setupUi(self, MergePurgeDialog):
        MergePurgeDialog.setObjectName("MergePurgeDialog")
        MergePurgeDialog.resize(782, 772)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MergePurgeDialog.sizePolicy().hasHeightForWidth())
        MergePurgeDialog.setSizePolicy(sizePolicy)
        self.tabWidget = QtGui.QTabWidget(MergePurgeDialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 716, 736))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.sortDropTab = QtGui.QWidget()
        self.sortDropTab.setObjectName("sortDropTab")
        self.verticalLayout = QtGui.QVBoxLayout(self.sortDropTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.sourcePathLabel = QtGui.QLabel(self.sortDropTab)
        self.sourcePathLabel.setObjectName("sourcePathLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.sourcePathLabel)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sourcePathSelectButton = QtGui.QPushButton(self.sortDropTab)
        self.sourcePathSelectButton.setObjectName("sourcePathSelectButton")
        self.gridLayout_2.addWidget(self.sourcePathSelectButton, 0, 1, 1, 1)
        self.sourcePathLineEdit = QtGui.QLineEdit(self.sortDropTab)
        self.sourcePathLineEdit.setObjectName("sourcePathLineEdit")
        self.gridLayout_2.addWidget(self.sourcePathLineEdit, 0, 0, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.gridLayout_2)
        self.destPathLabel = QtGui.QLabel(self.sortDropTab)
        self.destPathLabel.setObjectName("destPathLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.destPathLabel)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.destPathSelectButton = QtGui.QPushButton(self.sortDropTab)
        self.destPathSelectButton.setObjectName("destPathSelectButton")
        self.gridLayout_3.addWidget(self.destPathSelectButton, 0, 1, 1, 1)
        self.destPathLineEdit = QtGui.QLineEdit(self.sortDropTab)
        self.destPathLineEdit.setObjectName("destPathLineEdit")
        self.gridLayout_3.addWidget(self.destPathLineEdit, 0, 0, 1, 1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.gridLayout_3)
        self.sortOnLabel = QtGui.QLabel(self.sortDropTab)
        self.sortOnLabel.setObjectName("sortOnLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.sortOnLabel)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushGrid = QtGui.QGridLayout()
        self.pushGrid.setObjectName("pushGrid")
        self.sortOnRightView = QtGui.QListView(self.sortDropTab)
        self.sortOnRightView.setObjectName("sortOnRightView")
        self.pushGrid.addWidget(self.sortOnRightView, 0, 3, 1, 1)
        self.sortOnLeftView = QtGui.QListView(self.sortDropTab)
        self.sortOnLeftView.setObjectName("sortOnLeftView")
        self.pushGrid.addWidget(self.sortOnLeftView, 0, 0, 1, 1)
        self.btnGrid = QtGui.QGridLayout()
        self.btnGrid.setObjectName("btnGrid")
        self.sortOnRightButton = QtGui.QPushButton(self.sortDropTab)
        self.sortOnRightButton.setObjectName("sortOnRightButton")
        self.btnGrid.addWidget(self.sortOnRightButton, 0, 0, 1, 1)
        self.sortOnLeftButton = QtGui.QPushButton(self.sortDropTab)
        self.sortOnLeftButton.setObjectName("sortOnLeftButton")
        self.btnGrid.addWidget(self.sortOnLeftButton, 1, 0, 1, 1)
        self.pushGrid.addLayout(self.btnGrid, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.pushGrid, 0, 0, 1, 1)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.gridLayout)
        self.sortAscLabel = QtGui.QLabel(self.sortDropTab)
        self.sortAscLabel.setObjectName("sortAscLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.sortAscLabel)
        self.pushGrid_2 = QtGui.QGridLayout()
        self.pushGrid_2.setObjectName("pushGrid_2")
        self.sortAscRightView = QtGui.QListView(self.sortDropTab)
        self.sortAscRightView.setObjectName("sortAscRightView")
        self.pushGrid_2.addWidget(self.sortAscRightView, 0, 2, 1, 1)
        self.btnGrid_2 = QtGui.QGridLayout()
        self.btnGrid_2.setObjectName("btnGrid_2")
        self.sortAscRightButton = QtGui.QPushButton(self.sortDropTab)
        self.sortAscRightButton.setObjectName("sortAscRightButton")
        self.btnGrid_2.addWidget(self.sortAscRightButton, 0, 0, 1, 1)
        self.sortAscLeftButton = QtGui.QPushButton(self.sortDropTab)
        self.sortAscLeftButton.setObjectName("sortAscLeftButton")
        self.btnGrid_2.addWidget(self.sortAscLeftButton, 1, 0, 1, 1)
        self.pushGrid_2.addLayout(self.btnGrid_2, 0, 1, 1, 1)
        self.sortAscLeftView = QtGui.QListView(self.sortDropTab)
        self.sortAscLeftView.setObjectName("sortAscLeftView")
        self.pushGrid_2.addWidget(self.sortAscLeftView, 0, 0, 1, 1)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.pushGrid_2)
        self.dedupeOnLabel = QtGui.QLabel(self.sortDropTab)
        self.dedupeOnLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dedupeOnLabel.setOpenExternalLinks(False)
        self.dedupeOnLabel.setObjectName("dedupeOnLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.dedupeOnLabel)
        self.pushGrid_3 = QtGui.QGridLayout()
        self.pushGrid_3.setObjectName("pushGrid_3")
        self.dedupeOnRightView = QtGui.QListView(self.sortDropTab)
        self.dedupeOnRightView.setObjectName("dedupeOnRightView")
        self.pushGrid_3.addWidget(self.dedupeOnRightView, 0, 2, 1, 1)
        self.btnGrid_3 = QtGui.QGridLayout()
        self.btnGrid_3.setObjectName("btnGrid_3")
        self.dedupeOnRightButton = QtGui.QPushButton(self.sortDropTab)
        self.dedupeOnRightButton.setObjectName("dedupeOnRightButton")
        self.btnGrid_3.addWidget(self.dedupeOnRightButton, 0, 0, 1, 1)
        self.dedupeOnLeftButton = QtGui.QPushButton(self.sortDropTab)
        self.dedupeOnLeftButton.setObjectName("dedupeOnLeftButton")
        self.btnGrid_3.addWidget(self.dedupeOnLeftButton, 1, 0, 1, 1)
        self.pushGrid_3.addLayout(self.btnGrid_3, 0, 1, 1, 1)
        self.dedupeOnLeftView = QtGui.QListView(self.sortDropTab)
        self.dedupeOnLeftView.setObjectName("dedupeOnLeftView")
        self.pushGrid_3.addWidget(self.dedupeOnLeftView, 0, 0, 1, 1)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.pushGrid_3)
        self.verticalLayout.addLayout(self.formLayout)
        self.tabWidget.addTab(self.sortDropTab, "")
        self.mergeTab = QtGui.QWidget()
        self.mergeTab.setObjectName("mergeTab")
        self.gridLayoutWidget_7 = QtGui.QWidget(self.mergeTab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(30, 30, 621, 601))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_14 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.mergeFileTable = QtGui.QTableView(self.gridLayoutWidget_7)
        self.mergeFileTable.setObjectName("mergeFileTable")
        self.gridLayout_15.addWidget(self.mergeFileTable, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnAddMergeFile = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.btnAddMergeFile.setObjectName("btnAddMergeFile")
        self.horizontalLayout_5.addWidget(self.btnAddMergeFile)
        self.btnEditMergeFile = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.btnEditMergeFile.setObjectName("btnEditMergeFile")
        self.horizontalLayout_5.addWidget(self.btnEditMergeFile)
        self.btnDeleteMergeFile = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.btnDeleteMergeFile.setObjectName("btnDeleteMergeFile")
        self.horizontalLayout_5.addWidget(self.btnDeleteMergeFile)
        self.gridLayout_15.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_15, 1, 0, 1, 1)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.btnBrowseMergeFile = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.btnBrowseMergeFile.setObjectName("btnBrowseMergeFile")
        self.gridLayout_16.addWidget(self.btnBrowseMergeFile, 0, 0, 1, 1)
        self.mergeFileLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.mergeFileLineEdit.setObjectName("mergeFileLineEdit")
        self.gridLayout_16.addWidget(self.mergeFileLineEdit, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.tabWidget.addTab(self.mergeTab, "")
        self.suppressTab = QtGui.QWidget()
        self.suppressTab.setObjectName("suppressTab")
        self.gridLayoutWidget_5 = QtGui.QWidget(self.suppressTab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(30, 30, 621, 601))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_13 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sFileTable = QtGui.QTableView(self.gridLayoutWidget_5)
        self.sFileTable.setObjectName("sFileTable")
        self.gridLayout_6.addWidget(self.sFileTable, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAddSFile = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btnAddSFile.setObjectName("btnAddSFile")
        self.horizontalLayout_2.addWidget(self.btnAddSFile)
        self.btnEditSFile = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btnEditSFile.setObjectName("btnEditSFile")
        self.horizontalLayout_2.addWidget(self.btnEditSFile)
        self.btnDeleteSFile = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btnDeleteSFile.setObjectName("btnDeleteSFile")
        self.horizontalLayout_2.addWidget(self.btnDeleteSFile)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnBrowseSFile = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btnBrowseSFile.setObjectName("btnBrowseSFile")
        self.gridLayout_5.addWidget(self.btnBrowseSFile, 0, 0, 1, 1)
        self.sFileLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.sFileLineEdit.setObjectName("sFileLineEdit")
        self.gridLayout_5.addWidget(self.sFileLineEdit, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.suppressTab, "")
        self.fieldsTab = QtGui.QWidget()
        self.fieldsTab.setObjectName("fieldsTab")
        self.horizontalLayoutWidget = QtGui.QWidget(self.fieldsTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 691, 691))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fieldsTableView = QtGui.QTableView(self.horizontalLayoutWidget)
        self.fieldsTableView.setObjectName("fieldsTableView")
        self.horizontalLayout.addWidget(self.fieldsTableView)
        self.tabWidget.addTab(self.fieldsTab, "")

        self.retranslateUi(MergePurgeDialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MergePurgeDialog)

    def retranslateUi(self, MergePurgeDialog):
        MergePurgeDialog.setWindowTitle(QtGui.QApplication.translate("MergePurgeDialog", "Merge/Purge", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcePathLabel.setText(QtGui.QApplication.translate("MergePurgeDialog", "Source Path", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcePathSelectButton.setText(QtGui.QApplication.translate("MergePurgeDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.destPathLabel.setText(QtGui.QApplication.translate("MergePurgeDialog", "Destination Path", None, QtGui.QApplication.UnicodeUTF8))
        self.destPathSelectButton.setText(QtGui.QApplication.translate("MergePurgeDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.sortOnLabel.setText(QtGui.QApplication.translate("MergePurgeDialog", "Sort On", None, QtGui.QApplication.UnicodeUTF8))
        self.sortOnRightButton.setText(QtGui.QApplication.translate("MergePurgeDialog", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.sortOnLeftButton.setText(QtGui.QApplication.translate("MergePurgeDialog", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.sortAscLabel.setText(QtGui.QApplication.translate("MergePurgeDialog", "Sort Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.sortAscRightButton.setText(QtGui.QApplication.translate("MergePurgeDialog", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.sortAscLeftButton.setText(QtGui.QApplication.translate("MergePurgeDialog", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.dedupeOnLabel.setText(QtGui.QApplication.translate("MergePurgeDialog", "Dedupe On", None, QtGui.QApplication.UnicodeUTF8))
        self.dedupeOnRightButton.setText(QtGui.QApplication.translate("MergePurgeDialog", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.dedupeOnLeftButton.setText(QtGui.QApplication.translate("MergePurgeDialog", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sortDropTab), QtGui.QApplication.translate("MergePurgeDialog", "Sort/Dedupe", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddMergeFile.setText(QtGui.QApplication.translate("MergePurgeDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEditMergeFile.setText(QtGui.QApplication.translate("MergePurgeDialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeleteMergeFile.setText(QtGui.QApplication.translate("MergePurgeDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowseMergeFile.setText(QtGui.QApplication.translate("MergePurgeDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mergeTab), QtGui.QApplication.translate("MergePurgeDialog", "Merge", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSFile.setText(QtGui.QApplication.translate("MergePurgeDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEditSFile.setText(QtGui.QApplication.translate("MergePurgeDialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeleteSFile.setText(QtGui.QApplication.translate("MergePurgeDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowseSFile.setText(QtGui.QApplication.translate("MergePurgeDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.suppressTab), QtGui.QApplication.translate("MergePurgeDialog", "Suppress", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fieldsTab), QtGui.QApplication.translate("MergePurgeDialog", "Fields", None, QtGui.QApplication.UnicodeUTF8))

