# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'split.ui'
#
# Created: Sat Dec 17 20:18:32 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FileSplitDialog(object):
    def setupUi(self, FileSplitDialog):
        FileSplitDialog.setObjectName("FileSplitDialog")
        FileSplitDialog.resize(416, 359)
        self.verticalLayout = QtGui.QVBoxLayout(FileSplitDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.exportBasePathLabel = QtGui.QLabel(FileSplitDialog)
        self.exportBasePathLabel.setObjectName("exportBasePathLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.exportBasePathLabel)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnExportBrowse = QtGui.QPushButton(FileSplitDialog)
        self.btnExportBrowse.setObjectName("btnExportBrowse")
        self.gridLayout.addWidget(self.btnExportBrowse, 0, 1, 1, 1)
        self.lineEditExportPath = QtGui.QLineEdit(FileSplitDialog)
        self.lineEditExportPath.setObjectName("lineEditExportPath")
        self.gridLayout.addWidget(self.lineEditExportPath, 0, 0, 1, 1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.gridLayout)
        self.splitOnLabel = QtGui.QLabel(FileSplitDialog)
        self.splitOnLabel.setObjectName("splitOnLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.splitOnLabel)
        self.pushGrid = QtGui.QGridLayout()
        self.pushGrid.setObjectName("pushGrid")
        self.listViewSplitOnLeft = QtGui.QListView(FileSplitDialog)
        self.listViewSplitOnLeft.setObjectName("listViewSplitOnLeft")
        self.pushGrid.addWidget(self.listViewSplitOnLeft, 0, 0, 1, 1)
        self.listViewSplitOnRight = QtGui.QListView(FileSplitDialog)
        self.listViewSplitOnRight.setObjectName("listViewSplitOnRight")
        self.pushGrid.addWidget(self.listViewSplitOnRight, 0, 2, 1, 1)
        self.btnGrid = QtGui.QGridLayout()
        self.btnGrid.setObjectName("btnGrid")
        self.btnSplitOnPushRight = QtGui.QPushButton(FileSplitDialog)
        self.btnSplitOnPushRight.setObjectName("btnSplitOnPushRight")
        self.btnGrid.addWidget(self.btnSplitOnPushRight, 0, 0, 1, 1)
        self.btnSplitOnPushLeft = QtGui.QPushButton(FileSplitDialog)
        self.btnSplitOnPushLeft.setObjectName("btnSplitOnPushLeft")
        self.btnGrid.addWidget(self.btnSplitOnPushLeft, 1, 0, 1, 1)
        self.pushGrid.addLayout(self.btnGrid, 0, 1, 1, 1)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.pushGrid)
        self.sourcePathLabel = QtGui.QLabel(FileSplitDialog)
        self.sourcePathLabel.setObjectName("sourcePathLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.sourcePathLabel)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnSourcePathBrowse = QtGui.QPushButton(FileSplitDialog)
        self.btnSourcePathBrowse.setObjectName("btnSourcePathBrowse")
        self.gridLayout_2.addWidget(self.btnSourcePathBrowse, 0, 1, 1, 1)
        self.lineEditSourcePath = QtGui.QLineEdit(FileSplitDialog)
        self.lineEditSourcePath.setObjectName("lineEditSourcePath")
        self.gridLayout_2.addWidget(self.lineEditSourcePath, 0, 0, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.gridLayout_2)
        self.pushGrid_2 = QtGui.QGridLayout()
        self.pushGrid_2.setObjectName("pushGrid_2")
        self.listViewUseColsLeft = QtGui.QListView(FileSplitDialog)
        self.listViewUseColsLeft.setObjectName("listViewUseColsLeft")
        self.pushGrid_2.addWidget(self.listViewUseColsLeft, 0, 0, 1, 1)
        self.listViewUseColsRight = QtGui.QListView(FileSplitDialog)
        self.listViewUseColsRight.setObjectName("listViewUseColsRight")
        self.pushGrid_2.addWidget(self.listViewUseColsRight, 0, 2, 1, 1)
        self.btnGrid_2 = QtGui.QGridLayout()
        self.btnGrid_2.setObjectName("btnGrid_2")
        self.btnUseColsPushRight = QtGui.QPushButton(FileSplitDialog)
        self.btnUseColsPushRight.setObjectName("btnUseColsPushRight")
        self.btnGrid_2.addWidget(self.btnUseColsPushRight, 0, 0, 1, 1)
        self.btnUseColsPushLeft = QtGui.QPushButton(FileSplitDialog)
        self.btnUseColsPushLeft.setObjectName("btnUseColsPushLeft")
        self.btnGrid_2.addWidget(self.btnUseColsPushLeft, 1, 0, 1, 1)
        self.pushGrid_2.addLayout(self.btnGrid_2, 0, 1, 1, 1)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.pushGrid_2)
        self.useColumnsLabel = QtGui.QLabel(FileSplitDialog)
        self.useColumnsLabel.setObjectName("useColumnsLabel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.useColumnsLabel)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.maxRowsLabel = QtGui.QLabel(FileSplitDialog)
        self.maxRowsLabel.setObjectName("maxRowsLabel")
        self.gridLayout_3.addWidget(self.maxRowsLabel, 0, 1, 1, 1)
        self.lineEditMaxRows = QtGui.QLineEdit(FileSplitDialog)
        self.lineEditMaxRows.setObjectName("lineEditMaxRows")
        self.gridLayout_3.addWidget(self.lineEditMaxRows, 0, 2, 1, 1)
        self.checkBoxDropNulls = QtGui.QCheckBox(FileSplitDialog)
        self.checkBoxDropNulls.setObjectName("checkBoxDropNulls")
        self.gridLayout_3.addWidget(self.checkBoxDropNulls, 0, 0, 1, 1)
        self.formLayout.setLayout(7, QtGui.QFormLayout.FieldRole, self.gridLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(3, QtGui.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(6, QtGui.QFormLayout.LabelRole, spacerItem1)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtGui.QDialogButtonBox(FileSplitDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FileSplitDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), FileSplitDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), FileSplitDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FileSplitDialog)

    def retranslateUi(self, FileSplitDialog):
        FileSplitDialog.setWindowTitle(QtGui.QApplication.translate("FileSplitDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.exportBasePathLabel.setText(QtGui.QApplication.translate("FileSplitDialog", "Export Base Path", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportBrowse.setText(QtGui.QApplication.translate("FileSplitDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.splitOnLabel.setText(QtGui.QApplication.translate("FileSplitDialog", "Split On", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSplitOnPushRight.setText(QtGui.QApplication.translate("FileSplitDialog", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSplitOnPushLeft.setText(QtGui.QApplication.translate("FileSplitDialog", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcePathLabel.setText(QtGui.QApplication.translate("FileSplitDialog", "Source Path", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSourcePathBrowse.setText(QtGui.QApplication.translate("FileSplitDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUseColsPushRight.setText(QtGui.QApplication.translate("FileSplitDialog", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUseColsPushLeft.setText(QtGui.QApplication.translate("FileSplitDialog", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.useColumnsLabel.setText(QtGui.QApplication.translate("FileSplitDialog", "Use Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.maxRowsLabel.setText(QtGui.QApplication.translate("FileSplitDialog", "Max Rows", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxDropNulls.setText(QtGui.QApplication.translate("FileSplitDialog", "Drop Null Values", None, QtGui.QApplication.UnicodeUTF8))

