# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_connection.ui'
#
# Created: Sun Jan  1 02:12:39 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AlchemyConnectionDialog(object):
    def setupUi(self, AlchemyConnectionDialog):
        AlchemyConnectionDialog.setObjectName("AlchemyConnectionDialog")
        AlchemyConnectionDialog.resize(358, 324)
        self.verticalLayout_2 = QtGui.QVBoxLayout(AlchemyConnectionDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelDatabaseType = QtGui.QLabel(AlchemyConnectionDialog)
        self.labelDatabaseType.setObjectName("labelDatabaseType")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelDatabaseType)
        self.comboBoxDatabaseType = QtGui.QComboBox(AlchemyConnectionDialog)
        self.comboBoxDatabaseType.setObjectName("comboBoxDatabaseType")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxDatabaseType)
        self.labelConnectionURL = QtGui.QLabel(AlchemyConnectionDialog)
        self.labelConnectionURL.setObjectName("labelConnectionURL")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelConnectionURL)
        self.lineEditConnectionURL = QtGui.QLineEdit(AlchemyConnectionDialog)
        self.lineEditConnectionURL.setObjectName("lineEditConnectionURL")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditConnectionURL)
        self.labelHost = QtGui.QLabel(AlchemyConnectionDialog)
        self.labelHost.setObjectName("labelHost")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelHost)
        self.lineEditHost = QtGui.QLineEdit(AlchemyConnectionDialog)
        self.lineEditHost.setObjectName("lineEditHost")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditHost)
        self.labelUsername = QtGui.QLabel(AlchemyConnectionDialog)
        self.labelUsername.setObjectName("labelUsername")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelUsername)
        self.lineEditUsername = QtGui.QLineEdit(AlchemyConnectionDialog)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditUsername)
        self.labelPassword = QtGui.QLabel(AlchemyConnectionDialog)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelPassword)
        self.lineEditPassword = QtGui.QLineEdit(AlchemyConnectionDialog)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditPassword)
        self.labelDefaultDatabase = QtGui.QLabel(AlchemyConnectionDialog)
        self.labelDefaultDatabase.setObjectName("labelDefaultDatabase")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.labelDefaultDatabase)
        self.lineEditDefaultDatabase = QtGui.QLineEdit(AlchemyConnectionDialog)
        self.lineEditDefaultDatabase.setObjectName("lineEditDefaultDatabase")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEditDefaultDatabase)
        self.labelDatabaseAPI = QtGui.QLabel(AlchemyConnectionDialog)
        self.labelDatabaseAPI.setObjectName("labelDatabaseAPI")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.labelDatabaseAPI)
        self.comboBoxDatabaseAPI = QtGui.QComboBox(AlchemyConnectionDialog)
        self.comboBoxDatabaseAPI.setObjectName("comboBoxDatabaseAPI")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.comboBoxDatabaseAPI)
        self.labelPort = QtGui.QLabel(AlchemyConnectionDialog)
        self.labelPort.setObjectName("labelPort")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.labelPort)
        self.lineEditPort = QtGui.QLineEdit(AlchemyConnectionDialog)
        self.lineEditPort.setObjectName("lineEditPort")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEditPort)
        self.labelConnectionName = QtGui.QLabel(AlchemyConnectionDialog)
        self.labelConnectionName.setObjectName("labelConnectionName")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.labelConnectionName)
        self.lineEditConnectionName = QtGui.QLineEdit(AlchemyConnectionDialog)
        self.lineEditConnectionName.setObjectName("lineEditConnectionName")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEditConnectionName)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnTestConnection = QtGui.QPushButton(AlchemyConnectionDialog)
        self.btnTestConnection.setObjectName("btnTestConnection")
        self.gridLayout.addWidget(self.btnTestConnection, 0, 1, 1, 1)
        self.btnClear = QtGui.QPushButton(AlchemyConnectionDialog)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout.addWidget(self.btnClear, 0, 0, 1, 1)
        self.formLayout.setLayout(10, QtGui.QFormLayout.FieldRole, self.gridLayout)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtGui.QDialogButtonBox(AlchemyConnectionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(AlchemyConnectionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), AlchemyConnectionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AlchemyConnectionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AlchemyConnectionDialog)

    def retranslateUi(self, AlchemyConnectionDialog):
        AlchemyConnectionDialog.setWindowTitle(QtGui.QApplication.translate("AlchemyConnectionDialog", "New SQL Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDatabaseType.setText(QtGui.QApplication.translate("AlchemyConnectionDialog", "Database Type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDatabaseType.setToolTip(QtGui.QApplication.translate("AlchemyConnectionDialog", "Type of SQL Server to connect to", None, QtGui.QApplication.UnicodeUTF8))
        self.labelConnectionURL.setText(QtGui.QApplication.translate("AlchemyConnectionDialog", "Connection URL", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditConnectionURL.setToolTip(QtGui.QApplication.translate("AlchemyConnectionDialog", "A valid SQLAlchemy connection URL (no other fields needed)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHost.setText(QtGui.QApplication.translate("AlchemyConnectionDialog", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.labelUsername.setText(QtGui.QApplication.translate("AlchemyConnectionDialog", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPassword.setText(QtGui.QApplication.translate("AlchemyConnectionDialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDefaultDatabase.setText(QtGui.QApplication.translate("AlchemyConnectionDialog", "Default Database", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDatabaseAPI.setText(QtGui.QApplication.translate("AlchemyConnectionDialog", "Database API", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDatabaseAPI.setToolTip(QtGui.QApplication.translate("AlchemyConnectionDialog", "The database API for the selected SQL server", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPort.setText(QtGui.QApplication.translate("AlchemyConnectionDialog", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditPort.setToolTip(QtGui.QApplication.translate("AlchemyConnectionDialog", "The SQL server port", None, QtGui.QApplication.UnicodeUTF8))
        self.labelConnectionName.setText(QtGui.QApplication.translate("AlchemyConnectionDialog", "Connection Name", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTestConnection.setToolTip(QtGui.QApplication.translate("AlchemyConnectionDialog", "Test the connection", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTestConnection.setText(QtGui.QApplication.translate("AlchemyConnectionDialog", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClear.setToolTip(QtGui.QApplication.translate("AlchemyConnectionDialog", "Clear all lines with text in them.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClear.setText(QtGui.QApplication.translate("AlchemyConnectionDialog", "Clear", None, QtGui.QApplication.UnicodeUTF8))

