# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Jan 11 00:06:25 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DatabasesMainWindow(object):
    def setupUi(self, DatabasesMainWindow):
        DatabasesMainWindow.setObjectName("DatabasesMainWindow")
        DatabasesMainWindow.resize(785, 591)
        self.centralwidget = QtGui.QWidget(DatabasesMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView = QtGui.QTreeView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(50, 0))
        self.treeView.setMaximumSize(QtCore.QSize(175, 16777215))
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 350))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 0, 1, 1)
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 3, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBoxCurrentDatabase = QtGui.QComboBox(self.centralwidget)
        self.comboBoxCurrentDatabase.setObjectName("comboBoxCurrentDatabase")
        self.gridLayout_2.addWidget(self.comboBoxCurrentDatabase, 0, 1, 1, 1)
        self.labelCurrentDatabase = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCurrentDatabase.sizePolicy().hasHeightForWidth())
        self.labelCurrentDatabase.setSizePolicy(sizePolicy)
        self.labelCurrentDatabase.setObjectName("labelCurrentDatabase")
        self.gridLayout_2.addWidget(self.labelCurrentDatabase, 0, 0, 1, 1)
        self.comboBoxCurrentFile = QtGui.QComboBox(self.centralwidget)
        self.comboBoxCurrentFile.setObjectName("comboBoxCurrentFile")
        self.gridLayout_2.addWidget(self.comboBoxCurrentFile, 1, 1, 1, 1)
        self.labelCurrentFile = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCurrentFile.sizePolicy().hasHeightForWidth())
        self.labelCurrentFile.setSizePolicy(sizePolicy)
        self.labelCurrentFile.setObjectName("labelCurrentFile")
        self.gridLayout_2.addWidget(self.labelCurrentFile, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        DatabasesMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DatabasesMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 21))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtGui.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        DatabasesMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DatabasesMainWindow)
        self.statusbar.setObjectName("statusbar")
        DatabasesMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(DatabasesMainWindow)
        self.toolBar.setObjectName("toolBar")
        DatabasesMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAddDatabase = QtGui.QAction(DatabasesMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/standard_icons/add_database.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAddDatabase.setIcon(icon)
        self.actionAddDatabase.setObjectName("actionAddDatabase")
        self.actionRemove = QtGui.QAction(DatabasesMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/standard_icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove.setIcon(icon1)
        self.actionRemove.setObjectName("actionRemove")
        self.actionConnectToDatabase = QtGui.QAction(DatabasesMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/standard_icons/connected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnectToDatabase.setIcon(icon2)
        self.actionConnectToDatabase.setObjectName("actionConnectToDatabase")
        self.actionDisconnectFromDatabase = QtGui.QAction(DatabasesMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/standard_icons/disconnected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisconnectFromDatabase.setIcon(icon3)
        self.actionDisconnectFromDatabase.setObjectName("actionDisconnectFromDatabase")
        self.actionOpenFile = QtGui.QAction(DatabasesMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/standard_icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenFile.setIcon(icon4)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionImportFile = QtGui.QAction(DatabasesMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/standard_icons/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImportFile.setIcon(icon5)
        self.actionImportFile.setObjectName("actionImportFile")
        self.actionExportFile = QtGui.QAction(DatabasesMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/standard_icons/export_generic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportFile.setIcon(icon6)
        self.actionExportFile.setObjectName("actionExportFile")
        self.actionRefreshSchemas = QtGui.QAction(DatabasesMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/standard_icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefreshSchemas.setIcon(icon7)
        self.actionRefreshSchemas.setObjectName("actionRefreshSchemas")
        self.actionSaveText = QtGui.QAction(DatabasesMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/standard_icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveText.setIcon(icon8)
        self.actionSaveText.setObjectName("actionSaveText")
        self.actionSaveTextAs = QtGui.QAction(DatabasesMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/standard_icons/saveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveTextAs.setIcon(icon9)
        self.actionSaveTextAs.setObjectName("actionSaveTextAs")
        self.actionAddTable = QtGui.QAction(DatabasesMainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/standard_icons/insert_table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddTable.setIcon(icon10)
        self.actionAddTable.setObjectName("actionAddTable")
        self.actionExecuteQuery = QtGui.QAction(DatabasesMainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/standard_icons/lightning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExecuteQuery.setIcon(icon11)
        self.actionExecuteQuery.setObjectName("actionExecuteQuery")
        self.actionExecuteSelectedQuery = QtGui.QAction(DatabasesMainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/standard_icons/lightning2.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.actionExecuteSelectedQuery.setIcon(icon12)
        self.actionExecuteSelectedQuery.setObjectName("actionExecuteSelectedQuery")
        self.actionOpenQueryData = QtGui.QAction(DatabasesMainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/standard_icons/spreadsheet.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.actionOpenQueryData.setIcon(icon13)
        self.actionOpenQueryData.setObjectName("actionOpenQueryData")
        self.menuFiles.addAction(self.actionAddDatabase)
        self.menuFiles.addAction(self.actionAddTable)
        self.menuFiles.addAction(self.actionConnectToDatabase)
        self.menuFiles.addAction(self.actionDisconnectFromDatabase)
        self.menuFiles.addAction(self.actionOpenFile)
        self.menuFiles.addAction(self.actionOpenQueryData)
        self.menuFiles.addAction(self.actionImportFile)
        self.menuFiles.addAction(self.actionExportFile)
        self.menuFiles.addAction(self.actionExecuteQuery)
        self.menuFiles.addAction(self.actionExecuteSelectedQuery)
        self.menuFiles.addAction(self.actionRefreshSchemas)
        self.menuFiles.addAction(self.actionRemove)
        self.menuFiles.addAction(self.actionSaveText)
        self.menuFiles.addAction(self.actionSaveTextAs)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.toolBar.addAction(self.actionAddDatabase)
        self.toolBar.addAction(self.actionAddTable)
        self.toolBar.addAction(self.actionRemove)
        self.toolBar.addAction(self.actionConnectToDatabase)
        self.toolBar.addAction(self.actionDisconnectFromDatabase)
        self.toolBar.addAction(self.actionImportFile)
        self.toolBar.addAction(self.actionExportFile)
        self.toolBar.addAction(self.actionRefreshSchemas)
        self.toolBar.addAction(self.actionSaveText)
        self.toolBar.addAction(self.actionSaveTextAs)
        self.toolBar.addAction(self.actionOpenFile)
        self.toolBar.addAction(self.actionExecuteQuery)
        self.toolBar.addAction(self.actionExecuteSelectedQuery)
        self.toolBar.addAction(self.actionOpenQueryData)

        self.retranslateUi(DatabasesMainWindow)
        QtCore.QMetaObject.connectSlotsByName(DatabasesMainWindow)

    def retranslateUi(self, DatabasesMainWindow):
        DatabasesMainWindow.setWindowTitle(QtGui.QApplication.translate("DatabasesMainWindow", "Databases", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCurrentDatabase.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Current database", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCurrentDatabase.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCurrentFile.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Currently open file", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCurrentFile.setText(QtGui.QApplication.translate("DatabasesMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFiles.setTitle(QtGui.QApplication.translate("DatabasesMainWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("DatabasesMainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddDatabase.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Add Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddDatabase.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Add a database to the list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddDatabase.setShortcut(QtGui.QApplication.translate("DatabasesMainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Remove ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Remove selected item from list, database, or table.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnectToDatabase.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Connect to Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnectToDatabase.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Connect to selected database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnectToDatabase.setShortcut(QtGui.QApplication.translate("DatabasesMainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisconnectFromDatabase.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Disconnect From Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisconnectFromDatabase.setShortcut(QtGui.QApplication.translate("DatabasesMainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenFile.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenFile.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Open a .sql file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenFile.setShortcut(QtGui.QApplication.translate("DatabasesMainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportFile.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Import File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportFile.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Imports a file to the selected database/table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportFile.setShortcut(QtGui.QApplication.translate("DatabasesMainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportFile.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Export File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportFile.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Export a table/database to file(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportFile.setShortcut(QtGui.QApplication.translate("DatabasesMainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefreshSchemas.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Refresh Schemas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefreshSchemas.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Refresh database schema(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefreshSchemas.setShortcut(QtGui.QApplication.translate("DatabasesMainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveText.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Save File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveText.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Saves text in the text editor to file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveText.setShortcut(QtGui.QApplication.translate("DatabasesMainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveTextAs.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Save File As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveTextAs.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Save text in the editor to a new file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddTable.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Add Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExecuteQuery.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Execute Query", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExecuteQuery.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Execute current Query", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExecuteQuery.setShortcut(QtGui.QApplication.translate("DatabasesMainWindow", "Ctrl+Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExecuteSelectedQuery.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Execute Selected Query", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExecuteSelectedQuery.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Excecute only the selected SQL", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExecuteSelectedQuery.setShortcut(QtGui.QApplication.translate("DatabasesMainWindow", "Ctrl+Shift+Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenQueryData.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Open Query Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenQueryData.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Opens the current result query to a file view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenQueryData.setShortcut(QtGui.QApplication.translate("DatabasesMainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

from zeex.icons import icons_rc
