# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Fri Dec 30 07:57:53 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DatabasesMainWindow(object):
    def setupUi(self, DatabasesMainWindow):
        DatabasesMainWindow.setObjectName("DatabasesMainWindow")
        DatabasesMainWindow.resize(704, 580)
        self.centralwidget = QtGui.QWidget(DatabasesMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView = QtGui.QTreeView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(50, 0))
        self.treeView.setMaximumSize(QtCore.QSize(175, 16777215))
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        DatabasesMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DatabasesMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 21))
        self.menubar.setObjectName("menubar")
        DatabasesMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DatabasesMainWindow)
        self.statusbar.setObjectName("statusbar")
        DatabasesMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(DatabasesMainWindow)
        self.toolBar.setObjectName("toolBar")
        DatabasesMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAddDatabase = QtGui.QAction(DatabasesMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/standard_icons/add_database.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAddDatabase.setIcon(icon)
        self.actionAddDatabase.setObjectName("actionAddDatabase")
        self.actionRemoveDatabase = QtGui.QAction(DatabasesMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/standard_icons/delete_database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemoveDatabase.setIcon(icon1)
        self.actionRemoveDatabase.setObjectName("actionRemoveDatabase")
        self.actionConnectToDatabase = QtGui.QAction(DatabasesMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/standard_icons/connected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnectToDatabase.setIcon(icon2)
        self.actionConnectToDatabase.setObjectName("actionConnectToDatabase")
        self.actionDisconnectFromDatabase = QtGui.QAction(DatabasesMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/standard_icons/disconnected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisconnectFromDatabase.setIcon(icon3)
        self.actionDisconnectFromDatabase.setObjectName("actionDisconnectFromDatabase")
        self.actionAddTable = QtGui.QAction(DatabasesMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/standard_icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddTable.setIcon(icon4)
        self.actionAddTable.setObjectName("actionAddTable")
        self.actionImportFile = QtGui.QAction(DatabasesMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/standard_icons/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImportFile.setIcon(icon5)
        self.actionImportFile.setObjectName("actionImportFile")
        self.actionExportFile = QtGui.QAction(DatabasesMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/standard_icons/export_generic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportFile.setIcon(icon6)
        self.actionExportFile.setObjectName("actionExportFile")
        self.RefreshSchemas = QtGui.QAction(DatabasesMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/standard_icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RefreshSchemas.setIcon(icon7)
        self.RefreshSchemas.setObjectName("RefreshSchemas")
        self.actionSaveText = QtGui.QAction(DatabasesMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/standard_icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveText.setIcon(icon8)
        self.actionSaveText.setObjectName("actionSaveText")
        self.actionSaveTextAs = QtGui.QAction(DatabasesMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/standard_icons/saveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveTextAs.setIcon(icon9)
        self.actionSaveTextAs.setObjectName("actionSaveTextAs")
        self.toolBar.addAction(self.actionAddDatabase)
        self.toolBar.addAction(self.actionRemoveDatabase)
        self.toolBar.addAction(self.actionConnectToDatabase)
        self.toolBar.addAction(self.actionDisconnectFromDatabase)
        self.toolBar.addAction(self.actionAddTable)
        self.toolBar.addAction(self.actionImportFile)
        self.toolBar.addAction(self.actionExportFile)
        self.toolBar.addAction(self.RefreshSchemas)
        self.toolBar.addAction(self.actionSaveText)
        self.toolBar.addAction(self.actionSaveTextAs)

        self.retranslateUi(DatabasesMainWindow)
        QtCore.QMetaObject.connectSlotsByName(DatabasesMainWindow)

    def retranslateUi(self, DatabasesMainWindow):
        DatabasesMainWindow.setWindowTitle(QtGui.QApplication.translate("DatabasesMainWindow", "Databases", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("DatabasesMainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddDatabase.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Add Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddDatabase.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Add a database to the list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveDatabase.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Remove Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveDatabase.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Remove database from list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnectToDatabase.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Connect to Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnectToDatabase.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Connect to selected database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisconnectFromDatabase.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Disconnect From Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddTable.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Add Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddTable.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Add a table to the selected database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportFile.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Import File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportFile.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Imports a file to the selected database/table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportFile.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Export File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportFile.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Export a table/database to file(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.RefreshSchemas.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Refresh Schemas", None, QtGui.QApplication.UnicodeUTF8))
        self.RefreshSchemas.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Refresh database schema(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveText.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Save File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveText.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Saves text in the text editor to file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveTextAs.setText(QtGui.QApplication.translate("DatabasesMainWindow", "Save File As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveTextAs.setToolTip(QtGui.QApplication.translate("DatabasesMainWindow", "Save text in the editor to a new file", None, QtGui.QApplication.UnicodeUTF8))

from icons import icons_rc
