# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Zeke/Google Drive/dev/python/zeex/zeex/core/ui/sql/table_import.ui'
#
# Created: Mon Nov 13 22:57:19 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AlchemyTableImportDialog(object):
    def setupUi(self, AlchemyTableImportDialog):
        AlchemyTableImportDialog.setObjectName("AlchemyTableImportDialog")
        AlchemyTableImportDialog.resize(522, 231)
        self.horizontalLayout = QtGui.QHBoxLayout(AlchemyTableImportDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelSourcePath = QtGui.QLabel(AlchemyTableImportDialog)
        self.labelSourcePath.setObjectName("labelSourcePath")
        self.gridLayout.addWidget(self.labelSourcePath, 1, 0, 1, 1)
        self.btnEditSourcePath = QtGui.QPushButton(AlchemyTableImportDialog)
        self.btnEditSourcePath.setObjectName("btnEditSourcePath")
        self.gridLayout.addWidget(self.btnEditSourcePath, 1, 2, 1, 1)
        self.btnBrowseSourcePath = QtGui.QPushButton(AlchemyTableImportDialog)
        self.btnBrowseSourcePath.setObjectName("btnBrowseSourcePath")
        self.gridLayout.addWidget(self.btnBrowseSourcePath, 1, 3, 1, 1)
        self.lineEditSourcePath = QtGui.QLineEdit(AlchemyTableImportDialog)
        self.lineEditSourcePath.setObjectName("lineEditSourcePath")
        self.gridLayout.addWidget(self.lineEditSourcePath, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setObjectName("formLayout")
        self.labelConnectionName = QtGui.QLabel(AlchemyTableImportDialog)
        self.labelConnectionName.setObjectName("labelConnectionName")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelConnectionName)
        self.comboBoxConnectionName = QtGui.QComboBox(AlchemyTableImportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxConnectionName.sizePolicy().hasHeightForWidth())
        self.comboBoxConnectionName.setSizePolicy(sizePolicy)
        self.comboBoxConnectionName.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxConnectionName.setObjectName("comboBoxConnectionName")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxConnectionName)
        self.labelTableName = QtGui.QLabel(AlchemyTableImportDialog)
        self.labelTableName.setObjectName("labelTableName")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelTableName)
        self.lineEditTableName = QtGui.QLineEdit(AlchemyTableImportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTableName.sizePolicy().hasHeightForWidth())
        self.lineEditTableName.setSizePolicy(sizePolicy)
        self.lineEditTableName.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEditTableName.setObjectName("lineEditTableName")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditTableName)
        self.labelPrimaryKeyName = QtGui.QLabel(AlchemyTableImportDialog)
        self.labelPrimaryKeyName.setObjectName("labelPrimaryKeyName")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelPrimaryKeyName)
        self.comboBoxPrimaryKey = QtGui.QComboBox(AlchemyTableImportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPrimaryKey.sizePolicy().hasHeightForWidth())
        self.comboBoxPrimaryKey.setSizePolicy(sizePolicy)
        self.comboBoxPrimaryKey.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxPrimaryKey.setObjectName("comboBoxPrimaryKey")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBoxPrimaryKey)
        self.labelExistingTableOption = QtGui.QLabel(AlchemyTableImportDialog)
        self.labelExistingTableOption.setObjectName("labelExistingTableOption")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelExistingTableOption)
        self.comboBoxExistingTableOption = QtGui.QComboBox(AlchemyTableImportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxExistingTableOption.sizePolicy().hasHeightForWidth())
        self.comboBoxExistingTableOption.setSizePolicy(sizePolicy)
        self.comboBoxExistingTableOption.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxExistingTableOption.setObjectName("comboBoxExistingTableOption")
        self.comboBoxExistingTableOption.addItem("")
        self.comboBoxExistingTableOption.addItem("")
        self.comboBoxExistingTableOption.addItem("")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBoxExistingTableOption)
        self.labelAddMissingColumns = QtGui.QLabel(AlchemyTableImportDialog)
        self.labelAddMissingColumns.setObjectName("labelAddMissingColumns")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelAddMissingColumns)
        self.checkBoxAddMissingColumns = QtGui.QCheckBox(AlchemyTableImportDialog)
        self.checkBoxAddMissingColumns.setTristate(False)
        self.checkBoxAddMissingColumns.setObjectName("checkBoxAddMissingColumns")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.checkBoxAddMissingColumns)
        self.labelPrimaryKeyPriorit = QtGui.QLabel(AlchemyTableImportDialog)
        self.labelPrimaryKeyPriorit.setObjectName("labelPrimaryKeyPriorit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.labelPrimaryKeyPriorit)
        self.comboBoxPrimaryKeyPriority = QtGui.QComboBox(AlchemyTableImportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPrimaryKeyPriority.sizePolicy().hasHeightForWidth())
        self.comboBoxPrimaryKeyPriority.setSizePolicy(sizePolicy)
        self.comboBoxPrimaryKeyPriority.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxPrimaryKeyPriority.setObjectName("comboBoxPrimaryKeyPriority")
        self.comboBoxPrimaryKeyPriority.addItem("")
        self.comboBoxPrimaryKeyPriority.addItem("")
        self.comboBoxPrimaryKeyPriority.addItem("")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.comboBoxPrimaryKeyPriority)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtGui.QDialogButtonBox(AlchemyTableImportDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(AlchemyTableImportDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), AlchemyTableImportDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AlchemyTableImportDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AlchemyTableImportDialog)

    def retranslateUi(self, AlchemyTableImportDialog):
        AlchemyTableImportDialog.setWindowTitle(QtGui.QApplication.translate("AlchemyTableImportDialog", "Import Table", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSourcePath.setText(QtGui.QApplication.translate("AlchemyTableImportDialog", "Source Path", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEditSourcePath.setText(QtGui.QApplication.translate("AlchemyTableImportDialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowseSourcePath.setText(QtGui.QApplication.translate("AlchemyTableImportDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.labelConnectionName.setText(QtGui.QApplication.translate("AlchemyTableImportDialog", "Connection Name", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTableName.setText(QtGui.QApplication.translate("AlchemyTableImportDialog", "Table Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditTableName.setToolTip(QtGui.QApplication.translate("AlchemyTableImportDialog", "The name of the table to be created", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPrimaryKeyName.setText(QtGui.QApplication.translate("AlchemyTableImportDialog", "Primary Key", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPrimaryKey.setToolTip(QtGui.QApplication.translate("AlchemyTableImportDialog", "The name of the primary key for the table", None, QtGui.QApplication.UnicodeUTF8))
        self.labelExistingTableOption.setText(QtGui.QApplication.translate("AlchemyTableImportDialog", "Existing Table Option", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxExistingTableOption.setToolTip(QtGui.QApplication.translate("AlchemyTableImportDialog", "What should happen if the table already exists?", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxExistingTableOption.setItemText(0, QtGui.QApplication.translate("AlchemyTableImportDialog", "append", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxExistingTableOption.setItemText(1, QtGui.QApplication.translate("AlchemyTableImportDialog", "replace", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxExistingTableOption.setItemText(2, QtGui.QApplication.translate("AlchemyTableImportDialog", "fail", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAddMissingColumns.setText(QtGui.QApplication.translate("AlchemyTableImportDialog", "Add Missing Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAddMissingColumns.setToolTip(QtGui.QApplication.translate("AlchemyTableImportDialog", "Add extra columns in the data to the table to avoid errors", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPrimaryKeyPriorit.setText(QtGui.QApplication.translate("AlchemyTableImportDialog", "Primary Key Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPrimaryKeyPriority.setToolTip(QtGui.QApplication.translate("AlchemyTableImportDialog", "What should happen with duplicate primary keys?", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPrimaryKeyPriority.setItemText(0, QtGui.QApplication.translate("AlchemyTableImportDialog", "delete from table", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPrimaryKeyPriority.setItemText(1, QtGui.QApplication.translate("AlchemyTableImportDialog", "delete from import data", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPrimaryKeyPriority.setItemText(2, QtGui.QApplication.translate("AlchemyTableImportDialog", "ignore", None, QtGui.QApplication.UnicodeUTF8))

