# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Zeke/Google Drive/dev/python/zeex/zeex/core/ui/sql/table_description.ui'
#
# Created: Mon Nov 13 22:57:19 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AlchemyTableDescriptionDialog(object):
    def setupUi(self, AlchemyTableDescriptionDialog):
        AlchemyTableDescriptionDialog.setObjectName("AlchemyTableDescriptionDialog")
        AlchemyTableDescriptionDialog.resize(394, 429)
        self.verticalLayout_2 = QtGui.QVBoxLayout(AlchemyTableDescriptionDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelDatabaseHeader = QtGui.QLabel(AlchemyTableDescriptionDialog)
        self.labelDatabaseHeader.setObjectName("labelDatabaseHeader")
        self.gridLayout_3.addWidget(self.labelDatabaseHeader, 0, 1, 1, 1)
        self.labelRowCountHeader = QtGui.QLabel(AlchemyTableDescriptionDialog)
        self.labelRowCountHeader.setObjectName("labelRowCountHeader")
        self.gridLayout_3.addWidget(self.labelRowCountHeader, 0, 3, 1, 1)
        self.labelColumnCountHeader = QtGui.QLabel(AlchemyTableDescriptionDialog)
        self.labelColumnCountHeader.setObjectName("labelColumnCountHeader")
        self.gridLayout_3.addWidget(self.labelColumnCountHeader, 0, 4, 1, 1)
        self.labelColumnCountValue = QtGui.QLabel(AlchemyTableDescriptionDialog)
        self.labelColumnCountValue.setObjectName("labelColumnCountValue")
        self.gridLayout_3.addWidget(self.labelColumnCountValue, 1, 4, 1, 1)
        self.labelRowCountValue = QtGui.QLabel(AlchemyTableDescriptionDialog)
        self.labelRowCountValue.setObjectName("labelRowCountValue")
        self.gridLayout_3.addWidget(self.labelRowCountValue, 1, 3, 1, 1)
        self.labelTableNameHeader = QtGui.QLabel(AlchemyTableDescriptionDialog)
        self.labelTableNameHeader.setObjectName("labelTableNameHeader")
        self.gridLayout_3.addWidget(self.labelTableNameHeader, 0, 2, 1, 1)
        self.labelDatabaseValue = QtGui.QLabel(AlchemyTableDescriptionDialog)
        self.labelDatabaseValue.setObjectName("labelDatabaseValue")
        self.gridLayout_3.addWidget(self.labelDatabaseValue, 1, 1, 1, 1)
        self.labelTableNameValue = QtGui.QLabel(AlchemyTableDescriptionDialog)
        self.labelTableNameValue.setObjectName("labelTableNameValue")
        self.gridLayout_3.addWidget(self.labelTableNameValue, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtGui.QTableView(AlchemyTableDescriptionDialog)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 1, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnDeleteTable = QtGui.QPushButton(AlchemyTableDescriptionDialog)
        self.btnDeleteTable.setObjectName("btnDeleteTable")
        self.gridLayout_2.addWidget(self.btnDeleteTable, 3, 0, 1, 1)
        self.btnSave = QtGui.QPushButton(AlchemyTableDescriptionDialog)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout_2.addWidget(self.btnSave, 0, 0, 1, 1)
        self.btnDeleteColumn = QtGui.QPushButton(AlchemyTableDescriptionDialog)
        self.btnDeleteColumn.setObjectName("btnDeleteColumn")
        self.gridLayout_2.addWidget(self.btnDeleteColumn, 2, 0, 1, 1)
        self.btnAddColumn = QtGui.QPushButton(AlchemyTableDescriptionDialog)
        self.btnAddColumn.setObjectName("btnAddColumn")
        self.gridLayout_2.addWidget(self.btnAddColumn, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(AlchemyTableDescriptionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(AlchemyTableDescriptionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), AlchemyTableDescriptionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AlchemyTableDescriptionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AlchemyTableDescriptionDialog)

    def retranslateUi(self, AlchemyTableDescriptionDialog):
        AlchemyTableDescriptionDialog.setWindowTitle(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "Table Description", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDatabaseHeader.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRowCountHeader.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "Row Count", None, QtGui.QApplication.UnicodeUTF8))
        self.labelColumnCountHeader.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "Column Count", None, QtGui.QApplication.UnicodeUTF8))
        self.labelColumnCountValue.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRowCountValue.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTableNameHeader.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "Table Name", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDatabaseValue.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTableNameValue.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "Table Name", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeleteTable.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "Delete Table", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeleteColumn.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "Delete Column", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddColumn.setText(QtGui.QApplication.translate("AlchemyTableDescriptionDialog", "Add Column", None, QtGui.QApplication.UnicodeUTF8))

